'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace com.dell.xserv
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AssetServiceSoap", [Namespace]:="http://support.dell.com/WebServices/")>  _
    Partial Public Class AssetService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetAssetInformationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SysInfo.My.MySettings.Default.SysInfo_com_dell_xserv_AssetService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetAssetInformationCompleted As GetAssetInformationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://support.dell.com/WebServices/GetAssetInformation", RequestNamespace:="http://support.dell.com/WebServices/", ResponseNamespace:="http://support.dell.com/WebServices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAssetInformation(ByVal guid As System.Guid, ByVal applicationName As String, ByVal serviceTags As String) As Asset()
            Dim results() As Object = Me.Invoke("GetAssetInformation", New Object() {guid, applicationName, serviceTags})
            Return CType(results(0),Asset())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAssetInformationAsync(ByVal guid As System.Guid, ByVal applicationName As String, ByVal serviceTags As String)
            Me.GetAssetInformationAsync(guid, applicationName, serviceTags, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAssetInformationAsync(ByVal guid As System.Guid, ByVal applicationName As String, ByVal serviceTags As String, ByVal userState As Object)
            If (Me.GetAssetInformationOperationCompleted Is Nothing) Then
                Me.GetAssetInformationOperationCompleted = AddressOf Me.OnGetAssetInformationOperationCompleted
            End If
            Me.InvokeAsync("GetAssetInformation", New Object() {guid, applicationName, serviceTags}, Me.GetAssetInformationOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAssetInformationOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAssetInformationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAssetInformationCompleted(Me, New GetAssetInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://support.dell.com/WebServices/")>  _
    Partial Public Class Asset
        
        Private assetHeaderDataField As AssetHeaderData
        
        Private entitlementsField() As EntitlementData
        
        Private dupilcateAssetsField() As Asset
        
        Private userMessageField As String
        
        '''<remarks/>
        Public Property AssetHeaderData() As AssetHeaderData
            Get
                Return Me.assetHeaderDataField
            End Get
            Set
                Me.assetHeaderDataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Entitlements() As EntitlementData()
            Get
                Return Me.entitlementsField
            End Get
            Set
                Me.entitlementsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DupilcateAssets() As Asset()
            Get
                Return Me.dupilcateAssetsField
            End Get
            Set
                Me.dupilcateAssetsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserMessage() As String
            Get
                Return Me.userMessageField
            End Get
            Set
                Me.userMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://support.dell.com/WebServices/")>  _
    Partial Public Class AssetHeaderData
        
        Private serviceTagField As String
        
        Private systemIDField As String
        
        Private buidField As String
        
        Private regionField As String
        
        Private systemTypeField As String
        
        Private systemModelField As String
        
        Private systemShipDateField As Date
        
        '''<remarks/>
        Public Property ServiceTag() As String
            Get
                Return Me.serviceTagField
            End Get
            Set
                Me.serviceTagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SystemID() As String
            Get
                Return Me.systemIDField
            End Get
            Set
                Me.systemIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Buid() As String
            Get
                Return Me.buidField
            End Get
            Set
                Me.buidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Region() As String
            Get
                Return Me.regionField
            End Get
            Set
                Me.regionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SystemType() As String
            Get
                Return Me.systemTypeField
            End Get
            Set
                Me.systemTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SystemModel() As String
            Get
                Return Me.systemModelField
            End Get
            Set
                Me.systemModelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SystemShipDate() As Date
            Get
                Return Me.systemShipDateField
            End Get
            Set
                Me.systemShipDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://support.dell.com/WebServices/")>  _
    Partial Public Class EntitlementData
        
        Private serviceLevelCodeField As String
        
        Private serviceLevelDescriptionField As String
        
        Private providerField As String
        
        Private startDateField As Date
        
        Private endDateField As Date
        
        Private daysLeftField As Integer
        
        Private entitlementTypeField As EntitlementType
        
        '''<remarks/>
        Public Property ServiceLevelCode() As String
            Get
                Return Me.serviceLevelCodeField
            End Get
            Set
                Me.serviceLevelCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceLevelDescription() As String
            Get
                Return Me.serviceLevelDescriptionField
            End Get
            Set
                Me.serviceLevelDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Provider() As String
            Get
                Return Me.providerField
            End Get
            Set
                Me.providerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DaysLeft() As Integer
            Get
                Return Me.daysLeftField
            End Get
            Set
                Me.daysLeftField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EntitlementType() As EntitlementType
            Get
                Return Me.entitlementTypeField
            End Get
            Set
                Me.entitlementTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://support.dell.com/WebServices/")>  _
    Public Enum EntitlementType
        
        '''<remarks/>
        Expired
        
        '''<remarks/>
        Active
        
        '''<remarks/>
        Future
        
        '''<remarks/>
        Credited
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub GetAssetInformationCompletedEventHandler(ByVal sender As Object, ByVal e As GetAssetInformationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAssetInformationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Asset()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Asset())
            End Get
        End Property
    End Class
End Namespace
